import { Mono } from "./ui";

const EFFECTIVE_DATE = "May 2026";

function Section({ title, children }) {
  return (
    <div style={{ marginBottom: 28 }}>
      <Mono s={{ fontSize: 13, color: "var(--c)", letterSpacing: 2, display: "block", marginBottom: 8 }}>{title}</Mono>
      <div style={{ fontSize: 13, color: "var(--text2)", lineHeight: 1.8 }}>{children}</div>
    </div>
  );
}

export default function TermsView() {
  return (
    <div style={{ maxWidth: 720 }}>
      <div style={{ marginBottom: 28, paddingBottom: 18, borderBottom: "1px solid var(--border)" }}>
        <Mono s={{ fontSize: 13, color: "var(--text3)", letterSpacing: 3, display: "block", marginBottom: 5 }}>§ LEGAL</Mono>
        <h2 style={{ fontFamily: "'Bebas Neue'", fontSize: 34, letterSpacing: 1, color: "var(--text)", marginBottom: 6 }}>Terms of Service</h2>
        <Mono s={{ fontSize: 13, color: "var(--text3)" }}>Effective: {EFFECTIVE_DATE} · northstar / Northstar OS</Mono>
      </div>

      <div style={{ background: "var(--bg2)", border: "1px solid var(--border)", padding: "14px 18px", marginBottom: 28 }}>
        <div style={{ fontSize: 13, color: "var(--text2)", lineHeight: 1.7 }}>
          By downloading, installing, or using northstar ("the App"), you agree to these terms in full. If you do not agree, do not use the App.
        </div>
      </div>

      <Section title="01 — WHAT THE APP IS">
        northstar is a free, local-first personal development tool. It runs on your machine, stores all data locally, and uses the Anthropic Claude API — via <strong style={{ color: "var(--text)" }}>your own API key</strong> — to generate analysis and mission suggestions. The App is provided free of charge, as-is, with no warranties of any kind.
      </Section>

      <Section title="02 — YOUR DATA">
        All personal information you enter into northstar (goals, finances, relationships, health stats, etc.) is stored exclusively on your own device at <Mono s={{ fontSize: 13 }}>northstar-backend/data/northstar_data.json</Mono>. The developer of northstar has no access to this data, does not collect it, and does not transmit it to any server other than Anthropic's API at the moment you trigger a sync — using your own API key and subject to Anthropic's own privacy policy. You are solely responsible for the security of your device and the data stored on it.
      </Section>

      <Section title="03 — AI-GENERATED CONTENT">
        northstar uses large language models (Anthropic Claude) to generate analysis, scoring, feedback, and mission suggestions based on the information you provide. <strong style={{ color: "var(--text)" }}>This content is entirely AI-generated and must not be treated as professional advice of any kind</strong> — including but not limited to medical, psychological, financial, legal, nutritional, or fitness advice. AI outputs may be inaccurate, incomplete, inappropriate, offensive, or otherwise unsuitable. The developer accepts no responsibility for the content generated by the AI, or for any decisions you make based on it. Use your own judgement.
      </Section>

      <Section title="04 — NO LIABILITY FOR OFFENSIVE OR HARMFUL OUTPUT">
        AI models can produce outputs that are unexpected, insensitive, or offensive. The developer of northstar is not responsible for any distress, harm, or offence caused by AI-generated content produced by the App. If you encounter output you find harmful, you may clear it and re-run the analysis, or stop using the App.
      </Section>

      <Section title="05 — NO LIABILITY FOR DATA LOSS">
        northstar stores data in a single local JSON file. Hardware failure, accidental deletion, software bugs, or other events may result in loss of your data. The developer is not liable for any data loss. You are responsible for maintaining your own backups. The App includes a manual backup feature in Settings.
      </Section>

      <Section title="06 — API COSTS">
        northstar requires you to supply your own Anthropic API key. Any costs incurred through use of the Anthropic API are entirely your responsibility. The developer has no visibility into or control over your API usage or billing.
      </Section>

      <Section title="07 — NO WARRANTY">
        The App is provided "as is" without warranty of any kind, express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, or non-infringement. The developer does not warrant that the App will be error-free, uninterrupted, or free of security vulnerabilities.
      </Section>

      <Section title="08 — LIMITATION OF LIABILITY">
        To the fullest extent permitted by applicable law, the developer of northstar shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising out of or relating to your use of the App — including but not limited to loss of data, loss of income, emotional distress, or reliance on AI-generated content.
      </Section>

      <Section title="09 — CHANGES TO THESE TERMS">
        These terms may be updated from time to time. Continued use of the App following any update constitutes acceptance of the revised terms.
      </Section>

      <Section title="10 — CONTACT">
        For questions about these terms, contact the developer via the project's GitHub page.
      </Section>

      <div style={{ borderTop: "1px solid var(--border)", paddingTop: 18, marginTop: 8 }}>
        <Mono s={{ fontSize: 13, color: "var(--text3)" }}>© {new Date().getFullYear()} northstar / Northstar OS. All rights reserved.</Mono>
      </div>
    </div>
  );
}
